In [2]:
import numpy as np

# Bases 

### Bases 1

In [3]:
A = np.array( [[0.299, 0.587, 0.144], [0.5959, -0.2746, -0.3213], [0.2115, -0.5227, 0.3112]] )
RGB = np.array([[101], [142], [68]])

A @ RGB

array([[123.345 ],
       [ -0.6557],
       [-31.7003]])

In [4]:
A = np.array( [ [0.412,-0.124,-0.369],[0.209,0.031,0.462],[0.164,-0.171,0.191] ] ) 
RGB = np.array([[122], [112], [195]])
T = np.array([[0,0,0], [0,1,0],[0,0,1]])

print(np.linalg.inv(A) @ T @ A @ RGB)

[[188.25071049]
 [139.96676661]
 [163.15288256]]


### Bases 2

In [5]:
# x = av1 + bv2

x = np.array([[3],[2]])
v = np.array([[6,4], [1,3]])

np.linalg.inv(v) @ x 

array([[0.07142857],
       [0.64285714]])

In [6]:
# Bv = w

v = np.array([[0,0,1],[0,1,1],[1,1,1]])
w = np.array([[1.6,1.1,1],[1.6,1.1,1.9],[1,1,1]])

w @ np.linalg.inv(v)

array([[-0.1, -0.5,  1.6],
       [ 0.8, -0.5,  1.6],
       [ 0. ,  0. ,  1. ]])

In [7]:
# Qual o vetor equivalente a x na base v?

x = np.array([[3, 6, 3, 7, 4, 3, 8, 7, 1, 5]])
v = np.array([[8, 2, 6, 7, 0, 8, 6, 2, 4, 6], [0, 1, 9, 6, 0, 3, 7, 7, 9, 1], [8, 4, 8, 2, 5, 3, 9, 5, 2, 9], [4, 4, 5, 4, 1, 8, 9, 0, 8, 4], [1, 7, 5, 3, 5, 4, 8, 0, 6, 8], [2, 5, 6, 3, 6, 1, 0, 0, 7, 3], [3, 8, 5, 5, 1, 4, 1, 6, 7, 1], [2, 4, 7, 8, 6, 0, 2, 1, 2, 8], [8, 4, 5, 7, 0, 5, 0, 7, 5, 3], [4, 0, 3, 7, 0, 9, 6, 6, 4, 7]])

# Bx = Iv

x @ np.linalg.inv(v)

array([[-4.00026817, -1.00433291,  1.2881502 ,  4.39362368, -2.93987369,
        -1.68237023,  1.18689447,  2.79538677,  0.14800945,  0.77288265]])

In [8]:


x = np.array([[8, 7, 4, 7, 8, 1, 5, 4, 8, 9]])
v1 = np.array([[9, 6, 0]])
v2 = np.array([[3, 7, 4]])
v3 = np.array([[9, 7, 4]])

v = np.concatenate((v1,v2,v3), axis=0)

print(np.linalg.inv(v).tolist())

[[-2.4671622769447922e-17, -0.16666666666666666, 0.16666666666666666], [0.1666666666666667, 0.25, -0.25], [-0.2916666666666667, -0.0625, 0.3125]]


### Bases 3

In [9]:
d = 1
P = np.array([ [0,0,-d], [0, 1, 0], [-1/d, 0, 0] ]) 
ponto = np.array([[19],[18],[1]])

proj_1 = P @ ponto
proj_1

xp1 = proj_1[0]
yp1 = proj_1[1] / proj_1[2]

d = 3
P = np.array([ [0,0,-d], [0, 1, 0], [-1/d, 0, 0] ]) 

proj_2 = P @ ponto
proj_2

xp2 = proj_2[0]
yp2 = proj_2[1] / proj_2[2]

dist = ((xp1 - xp2)**2 + (yp1 - yp2)**2)**0.5
dist

array([2.75500049])